### PR TITLE
Chore: add React 17 to `peerDependencies`

### PR DESCRIPTION
**Pull request by nil4**
React 17 was released on 2020-10-20 ([announcement](https://reactjs.org/blog/2020/10/20/react-v17.html)); add it to `peerDependencies` to avoid NPM warnings.

### CODE REVIEW

**Comment by StringEpsilon** [comment]
Thanks. Will put out a patch release tomorrow. If I forget, just ping me.

**Comment by wachunei** [comment]
super friendly ping as we approach 20 hours from previous comment 😅

**Comment by StringEpsilon** [comment]
Published. Sorry for the wait.

**Comment by wachunei** [comment]
No worries, thank you!!

**Comment by billyjanitsch** [comment]
@StringEpsilon thanks for the release. However, I think there was an oversight:

Screen Shot 2020-10-22 at 2 20 13 PM

[0.4.0](https://diff.intrinsic.com/mini-create-react-context/0.3.2/0.4.0) was published 8 months ago (although the commit for that release does not seem to exist in the repo). Could you please publish 0.4.1 that includes the widened peer dep range?

**Comment by StringEpsilon** [comment]
Shoot. I'm on it.

**Comment by billyjanitsch** [comment]
Thanks @StringEpsilon, much appreciated!

**Pull request merged**
